version: "3.3"

services:
  db:
    image: postgres:alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root

  adminer:
    depends_on:
      - db
    image: adminer
    container_name: adminer_mysql
    restart: always
    ports:
      - "8080:8080"

networks:
  back:

volumes:
  mysql: